/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AstrologerWhereUniqueInput } from "../../astrologer/base/AstrologerWhereUniqueInput";
import { ValidateNested, IsOptional, IsDate, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { PredictionCreateNestedManyWithoutConsultationsInput } from "./PredictionCreateNestedManyWithoutConsultationsInput";
import { ReportCreateNestedManyWithoutConsultationsInput } from "./ReportCreateNestedManyWithoutConsultationsInput";
import { EnumConsultationStatus } from "./EnumConsultationStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ConsultationCreateInput {
  @ApiProperty({
    required: false,
    type: () => AstrologerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AstrologerWhereUniqueInput)
  @IsOptional()
  @Field(() => AstrologerWhereUniqueInput, {
    nullable: true,
  })
  astrologer?: AstrologerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  date?: Date | null;

  @ApiProperty({
    required: false,
    type: () => PredictionCreateNestedManyWithoutConsultationsInput,
  })
  @ValidateNested()
  @Type(() => PredictionCreateNestedManyWithoutConsultationsInput)
  @IsOptional()
  @Field(() => PredictionCreateNestedManyWithoutConsultationsInput, {
    nullable: true,
  })
  predictions?: PredictionCreateNestedManyWithoutConsultationsInput;

  @ApiProperty({
    required: false,
    type: () => ReportCreateNestedManyWithoutConsultationsInput,
  })
  @ValidateNested()
  @Type(() => ReportCreateNestedManyWithoutConsultationsInput)
  @IsOptional()
  @Field(() => ReportCreateNestedManyWithoutConsultationsInput, {
    nullable: true,
  })
  reports?: ReportCreateNestedManyWithoutConsultationsInput;

  @ApiProperty({
    required: false,
    enum: EnumConsultationStatus,
  })
  @IsEnum(EnumConsultationStatus)
  @IsOptional()
  @Field(() => EnumConsultationStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  time?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ConsultationCreateInput as ConsultationCreateInput };
