/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CallRecordCreateNestedManyWithoutUsersInput } from "./CallRecordCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ConsultationCreateNestedManyWithoutUsersInput } from "./ConsultationCreateNestedManyWithoutUsersInput";
import { KundliCreateNestedManyWithoutUsersInput } from "./KundliCreateNestedManyWithoutUsersInput";
import { ReportCreateNestedManyWithoutUsersInput } from "./ReportCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { VisitCreateNestedManyWithoutUsersInput } from "./VisitCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CallRecordCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CallRecordCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CallRecordCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  callRecords?: CallRecordCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ConsultationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ConsultationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ConsultationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  consultations?: ConsultationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => KundliCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => KundliCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => KundliCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  kundlis?: KundliCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => ReportCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ReportCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ReportCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  reports?: ReportCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => VisitCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VisitCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VisitCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  visits?: VisitCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
