/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CallRecordCreateNestedManyWithoutAstrologersInput } from "./CallRecordCreateNestedManyWithoutAstrologersInput";
import {
  ValidateNested,
  IsOptional,
  IsNumber,
  Min,
  Max,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ConsultationCreateNestedManyWithoutAstrologersInput } from "./ConsultationCreateNestedManyWithoutAstrologersInput";

@InputType()
class AstrologerCreateInput {
  @ApiProperty({
    required: false,
    type: () => CallRecordCreateNestedManyWithoutAstrologersInput,
  })
  @ValidateNested()
  @Type(() => CallRecordCreateNestedManyWithoutAstrologersInput)
  @IsOptional()
  @Field(() => CallRecordCreateNestedManyWithoutAstrologersInput, {
    nullable: true,
  })
  callRecords?: CallRecordCreateNestedManyWithoutAstrologersInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  consultationPrice?: number | null;

  @ApiProperty({
    required: false,
    type: () => ConsultationCreateNestedManyWithoutAstrologersInput,
  })
  @ValidateNested()
  @Type(() => ConsultationCreateNestedManyWithoutAstrologersInput)
  @IsOptional()
  @Field(() => ConsultationCreateNestedManyWithoutAstrologersInput, {
    nullable: true,
  })
  consultations?: ConsultationCreateNestedManyWithoutAstrologersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rating?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specialization?: string | null;
}

export { AstrologerCreateInput as AstrologerCreateInput };
